### PR TITLE
View connector2.1

### PR DESCRIPTION
**Pull request by dimitarsi**
This is another version of the jq viewConnector, but this time i think there is some issue with the up vector in Examine mode. I am not sure what should i do when the up vector is not [0,1,0].
Also I should get rid of the event param ( setOrientation), I can use the inverse ViewMatrix to get the position.

### CODE REVIEW

**Comment by tpaviot** [comment]
@dimitarsi Rather than adding a second static/js/jquery.viewConnector2.js file, can you please modify static/js/jquery.viewConnector.js so that it's easier to trace and review changes. That way, the modification of index.html would become unnecessary and you could squash your commits into one.

**Comment by tpaviot** [comment]
I ran a few tests. It runs quite well in Examine mode. However, there's an issue in Turntable mode, since the Back/Front/Side etc. cube behaviour overwrites the default behavior (the z vector [0, 0, 1] should be a limit). But it's pretty convincing.

**Comment by dimitarsi** [comment]
I kept the main code from the viewConnector but updated the orientation part and also the binding to the viewpoints. Also I change how the upVector is calculated - now it should be accurate :)

**Comment by tpaviot** [comment]
@tsturm FYI after your merge this pull request, I merged all the related commits into one and removed the trailing static/js/jquery.viewConnector2.js file.

**Pull request merged**
